# Generated by Django 5.1.7 on 2025-03-15 15:35

import djmoney.models.fields
import djmoney.models.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_usersettings_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="amount_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[
                    ("GBP", "British Pound"),
                    ("CAD", "Canadian Dollar"),
                    ("CNY", "Chinese Yuan"),
                    ("EUR", "Euro"),
                    ("JPY", "Japanese Yen"),
                    ("RUB", "Russian Ruble"),
                    ("USD", "US Dollar"),
                ],
                default="CHF",
                editable=False,
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="external_link",
            field=models.URLField(default="", null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="amount_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[
                    ("GBP", "British Pound"),
                    ("CAD", "Canadian Dollar"),
                    ("CNY", "Chinese Yuan"),
                    ("EUR", "Euro"),
                    ("JPY", "Japanese Yen"),
                    ("RUB", "Russian Ruble"),
                    ("USD", "US Dollar"),
                ],
                default="USD",
                editable=False,
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="usersettings",
            name="budget",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2,
                default=Decimal("100.0"),
                default_currency="USD",
                max_digits=10,
                validators=[djmoney.models.validators.MinMoneyValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="usersettings",
            name="budget_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[
                    ("GBP", "British Pound"),
                    ("CAD", "Canadian Dollar"),
                    ("CNY", "Chinese Yuan"),
                    ("EUR", "Euro"),
                    ("JPY", "Japanese Yen"),
                    ("RUB", "Russian Ruble"),
                    ("USD", "US Dollar"),
                ],
                default="USD",
                editable=False,
                max_length=3,
            ),
        ),
    ]
