# Generated by Django 5.1.7 on 2025-03-15 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_alter_subscription_amount_currency_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="external_link",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="last_reminder_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
