# Generated by Django 5.1.7 on 2025-03-15 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_subscription_external_link_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="external_link",
            field=models.CharField(blank=True, default=""),
        ),
    ]
