# Generated by Django 5.1.7 on 2025-03-15 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_alter_subscription_external_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="label",
            name="subscription",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.subscription",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="SubscriptionLabel",
        ),
    ]
