# Generated by Django 5.1.7 on 2025-03-21 13:01

import django.db.models.deletion
import djmoney.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_label_subscription_delete_subscriptionlabel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="label",
            name="subscription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="labels",
                to="api.subscription",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="amount_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[
                    ("GBP", "British Pound"),
                    ("CAD", "Canadian Dollar"),
                    ("CNY", "Chinese Yuan"),
                    ("EUR", "Euro"),
                    ("JPY", "Japanese Yen"),
                    ("RUB", "Russian Ruble"),
                    ("CHF", "Swiss Franc"),
                    ("USD", "US Dollar"),
                ],
                default="CHF",
                editable=False,
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="amount_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[
                    ("GBP", "British Pound"),
                    ("CAD", "Canadian Dollar"),
                    ("CNY", "Chinese Yuan"),
                    ("EUR", "Euro"),
                    ("JPY", "Japanese Yen"),
                    ("RUB", "Russian Ruble"),
                    ("CHF", "Swiss Franc"),
                    ("USD", "US Dollar"),
                ],
                default="USD",
                editable=False,
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="usersettings",
            name="budget_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[
                    ("GBP", "British Pound"),
                    ("CAD", "Canadian Dollar"),
                    ("CNY", "Chinese Yuan"),
                    ("EUR", "Euro"),
                    ("JPY", "Japanese Yen"),
                    ("RUB", "Russian Ruble"),
                    ("CHF", "Swiss Franc"),
                    ("USD", "US Dollar"),
                ],
                default="USD",
                editable=False,
                max_length=3,
            ),
        ),
    ]
