# Generated by Django 5.1.7 on 2025-03-21 17:36

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_alter_label_subscription_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="billed_at",
        ),
        migrations.AddField(
            model_name="subscription",
            name="date_end",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 3, 21, 17, 36, 0, 611086, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subscription",
            name="date_start",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
