# Generated by Django 5.1.7 on 2025-03-29 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0014_remove_subscription_last_reminder_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="name",
            field=models.CharField(default="", max_length=100),
        ),
    ]
