# Generated by Django 5.1.7 on 2025-04-21 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0017_usersettings_task"),
        ("django_celery_beat", "0019_alter_periodictasks_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usersettings",
            name="task",
        ),
        migrations.AddField(
            model_name="usersettings",
            name="monthly_report_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="plans_monitor",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_settings_plans_monitor",
                to="django_celery_beat.periodictask",
            ),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="report_task",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_settings_report",
                to="django_celery_beat.periodictask",
            ),
        ),
    ]
