# Generated by Django 5.1.7 on 2025-04-24 17:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0018_remove_usersettings_task_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersettings",
            name="remind_frequency",
            field=models.CharField(
                choices=[("weekly", "Weekly"), ("monthly", "Monthly")],
                default="weekly",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="usersettings",
            name="remind_within_days",
            field=models.BigIntegerField(default=30),
        ),
    ]
