# Generated by Django 5.1.7 on 2025-04-26 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0019_alter_usersettings_remind_frequency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="expired",
            field=models.BooleanField(default=False),
        ),
    ]
