# Generated by Django 5.1.7 on 2025-04-26 12:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0020_plan_expired"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="renewed",
            field=models.BooleanField(default=False),
        ),
    ]
