repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-merge-conflict
        name: '🌳 git · Detect conflict markers'
      - id: forbid-new-submodules
        name: '🌳 git · Prevent submodule creation'
      - id: check-added-large-files
        name: '🌳 git · Block large file commits'
        args: ['--maxkb=5000']
      - id: trailing-whitespace
        name: 'Remove trailing withspaces'
      - id: end-of-file-fixer
        name: 'Ensure end of file'
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.6.12
    hooks:
      - id: uv-lock
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.4
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format
